apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: foo
  # namespace: csync
spec:
  databaseVersion: "15.5.2"
  # availability:
  #   numberOfStandbys: 2
  #   enableStandbyAsReadReplica: true
  #   enableAutoFailover: true
  primarySpec:
    # schedulingconfig:
    #   tolerations:
    #    - effect: NoSchedule
    #      key: workloadtype
    #      operator: Equal
    #      value: db
    adminUser:
      passwordRef:
        name: db-pw-foo
    resources:
      memory: 2Gi
      cpu: 1
      disks:
      - name: DataDisk
        size: 2Gi
    dbLoadBalancerOptions:
      annotations:
        networking.gke.io/load-balancer-type: "internal"
  allowExternalIncomingTraffic: true
  # connectedModeSpec:
  #   gcpZone: us-central1-c
  #   clusterId: billing
  #   apiKeySecret: db-apikey-dbcluster-sample
  #   gcpProjectId: aedi-gbox
  #   displayLocation: SFO
